### ISSUE TITLE
Kanban board set-up

### ISSUE THREAD

**Issue by jfoyarzo** [jfoyarzo/Capstone-II#21]
Kanban board for 
In this milestone we have :

Used a Kanban board with filled-in tasks that have categories and time estimations to assign work in groups.
We Assigned Students A @jfoyarzo  and B @Miliyonayalew since we are a group of 2 Micronauts removed all Student C's tasks.

Link:
[Kanban Board](https://github.com/jfoyarzo/Capstone-II/projects/1)

**Comment by ShoiraTa** [comment]
### **STATUS: APPROVED  ✔️** 
------
Hi @jfoyarzo ,  

Your project is complete! Great job for nailing it right on the first attempt 🥇.Congratulations!  🎉💯🌟 

## Good Points 👍 
- Kanban board is set up correctly ✔️ 

![image](https://user-images.githubusercontent.com/77038610/192113867-880e831c-bf90-4a3b-a666-e2036b8c32ef.png)

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me [@shoirata] in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.


***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
